# Generated by Django 6.0.2 on 2026-03-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_productcategory_kitchentype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kitchentype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_users', to='api.kitchentype'),
        ),
    ]
